#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Schedule E/C — new area scaffolder (the "Obsidian folder creator").

Stands up a brand-new rental property (Sch. E) or business (Sch. C) area inside
this project, using 12 Sample Street (rental) / Olimazi (business) as the template.
Creates the folder skeleton, a parameterized copy of intake_scan.py with THIS
area's keywords (never the old area's), a starting CLAUDE.md, and — for a
rental — a copy of the tracker .xlsx to rename/clear; for a business — an empty
ledger CSV with the right header row. Never touches an existing area; refuses to
run if the target folder already exists.

Usage:
    python _System/new_area_setup.py --type rental  --name "45 Example Ave" --keywords "45 Example Ave,13 45 Example Ave,45 Example Ave"
    python _System/new_area_setup.py --type business --name "Acme Plumbing"   --keywords "acme,acme plumbing"

This is step 3 of onboarding — see ../ONBOARDING.md. Run AFTER you know the
drop-folder path and keyword list you want (ONBOARDING.md section 1); this
script does not invent keywords for you.
"""
from __future__ import annotations
import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # .../Schedule E and C

INTAKE_TEMPLATE = '''#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""{area_name} intake scanner — the free, local CAPTURE layer.

Generated by _System/new_area_setup.py from the Sch. E template. Scans capture
sources (the drop folder + Downloads), COPIES anything that looks like a
{noun} document/receipt/photo into _Inbox/, and logs it in a manifest for
review. Never deletes or moves the original, never books anything, zero
model tokens.

Usage:
    python _System/intake_scan.py            # capture + write manifest
    python _System/intake_scan.py --dry-run  # show what it would capture, copy nothing
"""
from __future__ import annotations
import hashlib
import json
import os
import shutil
import sys
from datetime import datetime, date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DROP = os.path.join(os.path.dirname(ROOT), "{drop_folder_name}")  # OneDrive-synced drop folder — confirm this path before relying on it (ONBOARDING.md step 1)
DOWNLOADS = os.path.join(os.path.expanduser("~"), "Downloads")
INBOX = os.path.join(ROOT, "_Inbox")
STATE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "intake_state.json")
MANIFEST = os.path.join(INBOX, "_manifest.md")

SUPPORTED = {{".pdf", ".jpg", ".jpeg", ".png", ".heic", ".webp", ".gif",
             ".tif", ".tiff", ".docx", ".eml", ".msg"}}
SKIP = {{".exe", ".msi", ".zip", ".msix", ".dmg", ".iso", ".py", ".md", ".json",
        ".js", ".ts", ".ini", ".gdoc", ".gsheet", ".lnk", ".tmp", ".crdownload"}}

# Downloads is a mixed bag (installers, resumes, unrelated files) so it requires
# a STRICT keyword match. Fill this in with names/vendors specific to
# {area_name} — generic words like "invoice" or "receipt" alone will vacuum up
# unrelated files. The drop folder stays capture-all (dropping a file there is
# explicit intent).
STRICT_KEYWORDS = [
{keyword_lines}
]
KEYWORDS = {{"{mode_key}": STRICT_KEYWORDS}}

CATEGORY_RULES = [
    # Add (keyword-tuple, "Category label") rules here as real documents show
    # what shows up — see the Sch. E template's CATEGORY_RULES for the pattern.
    (("invoice", "receipt"), "Expense — needs categorization"),
]


def sha1(path):
    h = hashlib.sha1()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def guess_category(name):
    low = name.lower()
    for keys, cat in CATEGORY_RULES:
        if any(k in low for k in keys):
            return cat
    return "Unsorted — needs review"


def name_matches(name, keywords):
    low = name.lower()
    return any(k in low for k in keywords)


def _iter_files(base, recursive):
    if recursive:
        for dp, _, fns in os.walk(base):
            for n in fns:
                yield os.path.join(dp, n)
    else:
        for n in os.listdir(base):
            p = os.path.join(base, n)
            if os.path.isfile(p):
                yield p


def candidates(extra_sources):
    srcs = []
    if os.path.isdir(DROP):
        srcs.append((DROP, "drop", "all", False))
    if os.path.isdir(DOWNLOADS):
        srcs.append((DOWNLOADS, "downloads", "{mode_key}", False))
    for path, mode in extra_sources:
        if os.path.isdir(path):
            lbl = "".join(c for c in os.path.basename(os.path.normpath(path)) if c.isalnum())[:12].upper() or "SCAN"
            srcs.append((path, lbl, mode, True))
        else:
            print(f"  (skipped — not a folder): {{path}}")
    for base, label, mode, recursive in srcs:
        for p in _iter_files(base, recursive):
            yield p, label, mode


def main():
    args = sys.argv[1:]
    dry = "--dry-run" in args
    extra, mode = [], None
    i = 0
    while i < len(args):
        if args[i] == "--scan" and i + 1 < len(args):
            extra.append(args[i + 1]); i += 2; continue
        if args[i] == "--mode" and i + 1 < len(args):
            mode = args[i + 1]; i += 2; continue
        i += 1
    extra_sources = [(p, mode or "{mode_key}") for p in extra]

    os.makedirs(INBOX, exist_ok=True)
    state = {{"captured": {{}}}}
    if os.path.exists(STATE):
        try:
            state = json.load(open(STATE, encoding="utf-8"))
        except Exception:
            pass
    seen = set(state.get("captured", {{}}).keys())

    captured, skipped = [], []
    for path, source, src_mode in candidates(extra_sources):
        ext = os.path.splitext(path)[1].lower()
        name = os.path.basename(path)
        if ext in SKIP or ext not in SUPPORTED:
            continue
        if src_mode != "all" and not name_matches(name, KEYWORDS.get(src_mode, STRICT_KEYWORDS)):
            continue
        try:
            digest = sha1(path)
        except Exception:
            continue
        if digest in seen:
            continue
        cat = guess_category(name)
        dest_name = f"{{source.upper()}}__{{name}}"
        dest = os.path.join(INBOX, dest_name)
        rec = {{"name": name, "source": source, "category": cat,
               "size": os.path.getsize(path), "src_path": path,
               "captured_at": datetime.now().isoformat(timespec="seconds"),
               "sha1": digest, "staged_as": dest_name}}
        if dry:
            skipped.append(rec)
            continue
        i = 1
        while os.path.exists(dest):
            dest = os.path.join(INBOX, f"{{source.upper()}}_{{i}}__{{name}}")
            i += 1
        shutil.copy2(path, dest)
        rec["staged_as"] = os.path.basename(dest)
        state.setdefault("captured", {{}})[digest] = rec
        seen.add(digest)
        captured.append(rec)

    if not dry:
        state["last_run"] = datetime.now().isoformat(timespec="seconds")
        with open(STATE, "w", encoding="utf-8") as f:
            json.dump(state, f, indent=2)
        write_manifest(state)

    label = "WOULD CAPTURE" if dry else "CAPTURED"
    items = skipped if dry else captured
    scanned = "drop + Downloads"
    if extra_sources:
        scanned += " + " + ", ".join(os.path.basename(os.path.normpath(p)) for p, _ in extra_sources)
    print(f"Intake scan {{date.today()}} — sources: {{scanned}}")
    print(f"  {{label}}: {{len(items)}} new file(s); _Inbox now tracks {{len(state.get('captured', {{}}))}} item(s).")
    for r in items:
        print(f"   [{{r['source']}}] {{r['name']}}  -> {{r['category']}}")
    if not items:
        print("  Nothing new to capture.")
    print(f"  Manifest: {{MANIFEST}}")
    return 0


def write_manifest(state):
    allrows = sorted(state.get("captured", {{}}).values(),
                     key=lambda r: r["captured_at"], reverse=True)
    awaiting = [r for r in allrows if r.get("disposition", "awaiting") == "awaiting"]
    done = [r for r in allrows if r.get("disposition", "awaiting") != "awaiting"]
    L = ["# {area_name} Intake — Review Queue",
         f"_Updated {{datetime.now():%Y-%m-%d %H:%M}}. Files captured from the drop "
         "folder and Downloads, staged for review. Originals were left in place; nothing "
         "is booked._\\n",
         f"**{{len(awaiting)}} item(s) awaiting review in `_Inbox/`** "
         f"({{len(done)}} already filed/dismissed).\\n",
         "| Captured | Source | File (staged name) | Guessed category | Size |",
         "|---|---|---|---|---|"]
    for r in awaiting:
        L.append(f"| {{r['captured_at'][:10]}} | {{r['source']}} | `{{r['staged_as']}}` | "
                 f"{{r['category']}} | {{r['size']/1024:.0f}} KB |")
    if not awaiting:
        L.append("| — | — | _queue empty_ | — | — |")
    if done:
        L.append("\\n## Filed / dismissed (kept in the log so they won't be re-captured)")
        L.append("| File | Disposition |")
        L.append("|---|---|")
        for r in done:
            L.append(f"| {{r['name']}} | {{r['disposition']}} |")
    L.append("\\n_After a row is booked into the tracker, set its disposition (or just delete "
             "its file from `_Inbox/`). The hash stays logged so it won't be re-captured._")
    with open(MANIFEST, "w", encoding="utf-8") as f:
        f.write("\\n".join(L))


if __name__ == "__main__":
    sys.exit(main())
'''

CLAUDE_MD_RENTAL_TEMPLATE = """# {area_name}

Rental property under the Schedule E / C system. Cloned from the 12 Sample Street template by
`_System/new_area_setup.py` on {today}. File setup and email-channel setup are project-wide —
see `..\\..\\ONBOARDING.md`. Architecture reference: `..\\..\\Sch. E\\_System\\README.md`.

## State
**Just scaffolded — not yet live.** Before relying on capture/review for this property:
1. Confirm the drop folder `{drop_folder_name}` exists (sibling to this project) and is
   OneDrive-synced, not Google Drive.
2. Fill in real keywords in `_System/intake_scan.py` (`STRICT_KEYWORDS`) — placeholders only so far.
3. Rename/build the tracker `.xlsx` for this property (copy 12 Sample Street's 4-tab structure:
   Income, Expenses, Sch. E Summary, Review — formulas only, no cached values).
4. Decide whether this property needs its own scheduled review task, or folds into an existing one.

## Where things live
- Ledger: `<Name>_SchE_Tracker.xlsx` (not yet created — see State above)
- Capture: `_System/intake_scan.py` · Review queue: `_Inbox/` · Out-of-scope: `_OutOfScope/` · Archive: `_Archive/`
- Reference docs: `Reference/` · Findings reports: `Reports/`

## Standing rule (inherited, load-bearing)
Every income/expense item lands on the IRS Schedule E line it actually belongs on — same
self-check as every other property under this project (see `..\\..\\CLAUDE.md`).

## Tone
Professional, direct, precise with numbers and dates. Confirm before logging or writing anything.
"""

CLAUDE_MD_BUSINESS_TEMPLATE = """# {area_name}

Self-employment (Schedule C) business under the Schedule E / C system. Scaffolded by
`_System/new_area_setup.py` on {today}. File setup and email-channel setup are project-wide —
see `..\\..\\ONBOARDING.md`. Architecture reference: `..\\..\\Sch. C\\_System\\README.md`.

## State
**Just scaffolded — not yet live.** Before relying on capture/review for this business:
1. Confirm the drop folder `{drop_folder_name}` exists (sibling to this project) and is
   OneDrive-synced, not Google Drive.
2. Fill in real keywords in `_System/intake_scan.py` (`STRICT_KEYWORDS`) — placeholders only so far.
3. Fill in `<Name>_SchC_Profile.md` (business basics) and confirm the ledger CSV header matches
   `Date, Type, Description, Amount, SchC_Category, SchC_Line, Notes`.
4. Decide whether this business needs its own scheduled review task, or folds into an existing one.

## Where things live
- Ledger: `<Name>_SchC_Ledger.csv` · Profile: `<Name>_SchC_Profile.md`
- Capture: `_System/intake_scan.py` · Review queue: `_Inbox/` · Out-of-scope: `_OutOfScope/` · Archive: `_Archive/`
- Reference docs: `Reference/` (IRS line map) · Findings reports: `Reports/`

## Standing rule (inherited, load-bearing)
Every income/expense item lands on the IRS Schedule C line it actually belongs on — Schedule C's
map is different from Schedule E's (see `..\\..\\CLAUDE.md`).

## Tone
Professional, direct, precise with numbers and dates. Confirm before logging or writing anything.
"""

LEDGER_CSV_HEADER = "Date,Type,Description,Amount,SchC_Category,SchC_Line,Notes\n"


NAME_STOPWORDS = {
    "co", "llc", "inc", "ltd", "the", "and", "of", "a", "an", "lane", "street",
    "st", "ave", "avenue", "dr", "drive", "rd", "road", "ct", "court", "way",
}


def build_intake_scan(area_name: str, noun: str, mode_key: str, drop_folder_name: str) -> str:
    full_name = area_name.strip().lower()
    words = [w.strip().lower() for w in area_name.replace(",", " ").split() if w.strip()]
    # Individual words only count as keywords if they're long enough AND not a
    # common short word/suffix (e.g. "Co", "LLC", "Lane") that would substring-match
    # unrelated files. The full name is always included as a safer phrase match.
    safe_words = [w for w in words if len(w) >= 4 and w not in NAME_STOPWORDS]
    keywords = [full_name] + safe_words if len(words) > 1 else words
    keyword_lines = ",\n".join(f'    "{k}"' for k in dict.fromkeys(keywords))  # dedupe, keep order
    escaped_drop_folder = drop_folder_name.replace("\\", "\\\\").replace('"', '\\"')
    return INTAKE_TEMPLATE.format(
        area_name=area_name, noun=noun, mode_key=mode_key,
        drop_folder_name=escaped_drop_folder, keyword_lines=keyword_lines,
    )


def legacy_main():
    ap = argparse.ArgumentParser(description="Scaffold a new Sch. E (rental) or Sch. C (business) area.")
    ap.add_argument("--type", required=True, choices=["rental", "business"])
    ap.add_argument("--name", required=True, help='Display name, e.g. "45 Example Ave" or "Acme Plumbing"')
    ap.add_argument("--keywords", default="", help="Comma-separated keywords for the Downloads filter (optional — name words are always included)")
    ap.add_argument("--drop-folder", default=None, help='Drop folder name (default: "<Name> Inbox")')
    args = ap.parse_args()

    parent = "Sch. E" if args.type == "rental" else "Sch. C"
    parent_path = os.path.join(PROJECT_ROOT, parent)
    if not os.path.isdir(parent_path):
        print(f"ERROR: expected {parent_path} to exist — run this from inside the Schedule E and C project.")
        return 1

    area_path = os.path.join(parent_path, args.name)
    if os.path.exists(area_path):
        print(f"ERROR: {area_path} already exists — refusing to overwrite. Pick a different --name or remove it first.")
        return 1

    drop_folder_name = args.drop_folder or f"{args.name} Inbox"
    today = __import__("datetime").date.today().isoformat()

    for sub in ("_Inbox", "_Archive", "_OutOfScope", "_System", "Reference", "Reports"):
        os.makedirs(os.path.join(area_path, sub), exist_ok=True)

    noun = "rental property" if args.type == "rental" else "business"
    mode_key = "property" if args.type == "rental" else "business"
    intake_src = build_intake_scan(args.name, noun, mode_key, drop_folder_name)
    if args.keywords.strip():
        extra = [k.strip().lower() for k in args.keywords.split(",") if k.strip()]
        extra_lines = ",\n".join(f'    "{k}"' for k in extra)
        intake_src = intake_src.replace(
            "STRICT_KEYWORDS = [\n", f"STRICT_KEYWORDS = [\n{extra_lines},\n", 1
        )
    with open(os.path.join(area_path, "_System", "intake_scan.py"), "w", encoding="utf-8") as f:
        f.write(intake_src)

    claude_tpl = CLAUDE_MD_RENTAL_TEMPLATE if args.type == "rental" else CLAUDE_MD_BUSINESS_TEMPLATE
    with open(os.path.join(area_path, "CLAUDE.md"), "w", encoding="utf-8") as f:
        f.write(claude_tpl.format(area_name=args.name, today=today, drop_folder_name=drop_folder_name))

    if args.type == "rental":
        template_xlsx = None
        for fn in os.listdir(os.path.join(PROJECT_ROOT, "Sch. E")):
            if fn.lower().endswith(".xlsx") and "tracker" in fn.lower():
                template_xlsx = os.path.join(PROJECT_ROOT, "Sch. E", fn)
                break
        if template_xlsx:
            dest_xlsx = os.path.join(area_path, f"2026_{args.name.replace(' ', '')}_SchE_Tracker.xlsx")
            shutil.copy2(template_xlsx, dest_xlsx)
            print(f"  Copied tracker template -> {dest_xlsx}")
            print("  ACTION NEEDED: open it, clear out 12 Sample Street's data rows, keep the formulas/tabs.")
        else:
            print("  WARNING: no *Tracker*.xlsx found in Sch. E/ to copy as a template — build one manually (see Sch. E/_System/README.md).")
    else:
        ledger_path = os.path.join(area_path, f"{args.name.replace(' ', '_')}_SchC_Ledger.csv")
        with open(ledger_path, "w", encoding="utf-8") as f:
            f.write(LEDGER_CSV_HEADER)
        print(f"  Created empty ledger -> {ledger_path}")
        profile_path = os.path.join(area_path, f"{args.name.replace(' ', '_')}_SchC_Profile.md")
        with open(profile_path, "w", encoding="utf-8") as f:
            f.write(f"# {args.name} — Sch. C Profile\n\n_Fill in: entity type, start date, principal activity, typical income/expense lines._\n")
        print(f"  Created profile skeleton -> {profile_path}")

    print(f"\n{args.type.title()} area scaffolded: {area_path}")
    print("\nNext steps (ONBOARDING.md section 1 — confirm before relying on capture):")
    print(f"  1. Create the drop folder as a sibling of this project: ..\\{drop_folder_name}\\ (OneDrive-synced)")
    print(f"  2. Review/extend STRICT_KEYWORDS in {os.path.join(area_path, '_System', 'intake_scan.py')}")
    print(f"  3. Decide if this area needs its own scheduled review task")
    print("  4. Re-check ONBOARDING.md section 2 — confirm which email channel can actually send for this area")
    return 0


def safe_folder_name(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug or "olimazi-tracker"


def parse_lines(raw: str) -> list[int]:
    if not raw.strip():
        return list(range(3, 20))
    lines = sorted({int(value.strip()) for value in raw.split(",") if value.strip()})
    invalid = [line for line in lines if line < 3 or line > 19]
    if invalid:
        raise ValueError("Schedule lines must be comma-separated numbers from 3 through 19.")
    return lines


def main():
    ap = argparse.ArgumentParser(
        description="Create an empty Olimazi rental or small-business tracker."
    )
    ap.add_argument("--type", required=True, choices=["rental", "business"])
    ap.add_argument("--name", required=True, help="Property or business display name")
    ap.add_argument(
        "--output",
        help='Tracker folder (default: "~/Olimazi Trackers/<name>")',
    )
    ap.add_argument(
        "--applicable-lines",
        default="",
        help="Comma-separated schedule line numbers from 3 through 19",
    )
    ap.add_argument(
        "--mortgage",
        choices=["yes", "no", "not-applicable"],
        default="not-applicable",
    )
    ap.add_argument(
        "--document-folder",
        action="append",
        default=[],
        help="Folder where documents arrive; repeat for multiple folders",
    )
    ap.add_argument(
        "--email",
        default="",
        help="Email address to record for future intake; no email connection is created",
    )
    ap.add_argument(
        "--keywords",
        default="",
        help="Comma-separated filename keywords for the generated intake scanner",
    )
    ap.add_argument(
        "--drop-folder",
        default=None,
        help="Primary document drop folder; defaults to the first --document-folder",
    )
    args = ap.parse_args()

    try:
        applicable_lines = parse_lines(args.applicable_lines)
    except ValueError as exc:
        ap.error(str(exc))

    default_output = Path.home() / "Olimazi Trackers" / safe_folder_name(args.name)
    area_path = Path(args.output).expanduser().resolve() if args.output else default_output
    if area_path.exists():
        print(f"ERROR: {area_path} already exists — refusing to overwrite.")
        return 1

    document_folders = [
        str(Path(folder).expanduser().resolve()) for folder in args.document_folder
    ]
    drop_folder_name = args.drop_folder or (
        document_folders[0] if document_folders else str(area_path / "document-drop")
    )

    for sub in ("_Inbox", "_Archive", "_OutOfScope", "_System", "Reference", "Reports"):
        (area_path / sub).mkdir(parents=True, exist_ok=True)

    noun = "rental property" if args.type == "rental" else "business"
    mode_key = "property" if args.type == "rental" else "business"
    intake_src = build_intake_scan(args.name, noun, mode_key, drop_folder_name)
    if args.keywords.strip():
        extra = [k.strip().lower() for k in args.keywords.split(",") if k.strip()]
        extra_lines = ",\n".join(f'    "{k}"' for k in extra)
        intake_src = intake_src.replace(
            "STRICT_KEYWORDS = [\n", f"STRICT_KEYWORDS = [\n{extra_lines},\n", 1
        )
    (area_path / "_System" / "intake_scan.py").write_text(
        intake_src, encoding="utf-8"
    )

    sys.path.insert(0, PROJECT_ROOT)
    from fixtures.make_fixture import build_empty_workbook

    tracker_path = area_path / "tracker.xlsx"
    build_empty_workbook(args.name, tracker_path, applicable_lines, args.type)

    profile = {
        "profile_version": 1,
        "name": args.name,
        "type": args.type,
        "applicable_lines": applicable_lines,
        "mortgage": (
            True if args.mortgage == "yes" else False if args.mortgage == "no" else None
        ),
        "document_folders": document_folders,
        "email_intake": {
            "address": args.email,
            "status": "recorded_only",
        },
        "anticipated_items": [],
        "engine_support": (
            "schedule_e" if args.type == "rental" else "schedule_c_setup_preview"
        ),
    }
    with open(area_path / "profile.json", "w", encoding="utf-8") as f:
        json.dump(profile, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Created empty {args.type} tracker: {area_path}")
    print(f"  Workbook: {tracker_path}")
    print(f"  Profile:  {area_path / 'profile.json'}")
    if args.type == "business":
        print("  NOTE: Schedule C reconciliation is still being adapted; this is a setup preview.")
    print("  Email intake was recorded only; no email connection was created.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
